// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801063454_AddChantierDatesToUser")]
    partial class AddChantierDatesToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Devis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateDevis")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateValidite")
                        .HasColumnType("date");

                    b.Property<string>("DelaiExecution")
                        .HasColumnType("text");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("ExtractionBrute")
                        .HasColumnType("text");

                    b.Property<string>("FichierPdfPath")
                        .HasColumnType("text");

                    b.Property<string>("Lot")
                        .HasColumnType("text");

                    b.Property<string>("NumeroDevis")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReponseBrute")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalHt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TotalTtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TvaMontant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TvaTaux")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("TypeLot")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("UserId", "EntrepriseId", "NumeroDevis")
                        .IsUnique()
                        .HasFilter("\"NumeroDevis\" IS NOT NULL");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("backend.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactNom")
                        .HasColumnType("text");

                    b.Property<string>("ContactTel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Siret")
                        .IsUnique();

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateEcheance")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFacture")
                        .HasColumnType("date");

                    b.Property<int?>("DevisId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("ExtractionBrute")
                        .HasColumnType("text");

                    b.Property<string>("FichierPdfPath")
                        .HasColumnType("text");

                    b.Property<string>("NumeroFacture")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReponseBrute")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalHt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TotalTtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TvaMontant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TvaTaux")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TypeFacture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TypeLot")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("UserId", "EntrepriseId", "NumeroFacture")
                        .IsUnique()
                        .HasFilter("\"NumeroFacture\" IS NOT NULL");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("backend.Models.LigneFacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FactureId")
                        .HasColumnType("integer");

                    b.Property<int?>("LignePosteId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Quantite")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TotalLigne")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unite")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.HasIndex("LignePosteId");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("backend.Models.LignePoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DevisId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Quantite")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TotalLigne")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unite")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.ToTable("LignesPoste");
                });

            modelBuilder.Entity("backend.Models.LlmExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Batch")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("DureeMs")
                        .HasColumnType("integer");

                    b.Property<string>("Erreur")
                        .HasColumnType("text");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NbImages")
                        .HasColumnType("integer");

                    b.Property<string>("ReponseBrute")
                        .HasColumnType("text");

                    b.Property<bool>("Succes")
                        .HasColumnType("boolean");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TypeDocument", "DocumentId");

                    b.ToTable("LlmExchanges");
                });

            modelBuilder.Entity("backend.Models.PieceJointe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FactureId")
                        .HasColumnType("integer");

                    b.Property<string>("Libelle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TailleOctets")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("PiecesJointes");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateDebutChantier")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateLivraisonPrevue")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Devis", b =>
                {
                    b.HasOne("backend.Models.Entreprise", "Entreprise")
                        .WithMany("Devis")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Entreprise", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.HasOne("backend.Models.Devis", "Devis")
                        .WithMany("Factures")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Entreprise", "Entreprise")
                        .WithMany("Factures")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devis");

                    b.Navigation("Entreprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.LigneFacture", b =>
                {
                    b.HasOne("backend.Models.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.LignePoste", "LignePoste")
                        .WithMany()
                        .HasForeignKey("LignePosteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facture");

                    b.Navigation("LignePoste");
                });

            modelBuilder.Entity("backend.Models.LignePoste", b =>
                {
                    b.HasOne("backend.Models.Devis", "Devis")
                        .WithMany("Lignes")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("backend.Models.PieceJointe", b =>
                {
                    b.HasOne("backend.Models.Facture", "Facture")
                        .WithMany("PiecesJointes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("backend.Models.Devis", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("backend.Models.Entreprise", b =>
                {
                    b.Navigation("Devis");

                    b.Navigation("Factures");
                });

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("PiecesJointes");
                });
#pragma warning restore 612, 618
        }
    }
}
