// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701150221_MakeEntrepriseOptionalOnDevisFacture")]
    partial class MakeEntrepriseOptionalOnDevisFacture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Devis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DateDevis")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateValidite")
                        .HasColumnType("date");

                    b.Property<string>("DelaiExecution")
                        .HasColumnType("longtext");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("ExtractionBrute")
                        .HasColumnType("longtext");

                    b.Property<string>("FichierPdfPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Lot")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDevis")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalHt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalTtc")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TvaMontant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TvaTaux")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("TypeLot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId", "NumeroDevis")
                        .IsUnique()
                        .HasFilter("NumeroDevis IS NOT NULL");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("backend.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNom")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactTel")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Siret")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Siret")
                        .IsUnique();

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DateEcheance")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFacture")
                        .HasColumnType("date");

                    b.Property<int?>("DevisId")
                        .HasColumnType("int");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("ExtractionBrute")
                        .HasColumnType("longtext");

                    b.Property<string>("FichierPdfPath")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroFacture")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalHt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalTtc")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TvaMontant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TvaTaux")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TypeFacture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TypeLot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.HasIndex("EntrepriseId", "NumeroFacture")
                        .IsUnique()
                        .HasFilter("NumeroFacture IS NOT NULL");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("backend.Models.LigneFacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FactureId")
                        .HasColumnType("int");

                    b.Property<int?>("LignePosteId")
                        .HasColumnType("int");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Quantite")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalLigne")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Unite")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.HasIndex("LignePosteId");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("backend.Models.LignePoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DevisId")
                        .HasColumnType("int");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Quantite")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalLigne")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Unite")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.ToTable("LignesPoste");
                });

            modelBuilder.Entity("backend.Models.Devis", b =>
                {
                    b.HasOne("backend.Models.Entreprise", "Entreprise")
                        .WithMany("Devis")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.HasOne("backend.Models.Devis", "Devis")
                        .WithMany("Factures")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Entreprise", "Entreprise")
                        .WithMany("Factures")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Devis");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("backend.Models.LigneFacture", b =>
                {
                    b.HasOne("backend.Models.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.LignePoste", "LignePoste")
                        .WithMany()
                        .HasForeignKey("LignePosteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facture");

                    b.Navigation("LignePoste");
                });

            modelBuilder.Entity("backend.Models.LignePoste", b =>
                {
                    b.HasOne("backend.Models.Devis", "Devis")
                        .WithMany("Lignes")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("backend.Models.Devis", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("backend.Models.Entreprise", b =>
                {
                    b.Navigation("Devis");

                    b.Navigation("Factures");
                });

            modelBuilder.Entity("backend.Models.Facture", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
